sliders = abberationAmount noiseSize vignetteAmount fogStrenth waterBlueness foliageGreenAmount starBrightness sunMoonBrightness

screen.columns = 2


profile.original = !chromaticAbberation vignetteAmount:0.2 noiseSize:1200.0
profile.cinematic = chromaticAbberation vignetteAmount:0.7 noiseSize:800.0

screen = ABOUT <profile> <empty> <empty> [suboptions] vignette noiseToggle fogToggle fogSkyOverlap fogStrenth vignetteAmount waterBlueness
screen.suboptions = grayscaleLight noWaterTransparency noiseSize foliageGreenAmount abberationAmount starBrightness sunMoonBrightness

